name: Build

on:
  push:
    branches:
      - version/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Build
        run: trunk build --public-url . --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
